name: Library test

on:
  push:
    paths:
      - library/**
      - test/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.100
    - name: Restore dependencies
      run: dotnet restore
      working-directory: test
    - name: Build
      run: dotnet build --no-restore
      working-directory: test
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter Name!=TestDay1Part1
      working-directory: test
